--DROP TABLE IF EXISTS TB_USER;

--CREATE TABLE TB_USER (
	--id INTEGER PRIMARY KEY AUTO_INCREMENT,
	--name VARCHAR(255) NOT NULL,
	--password VARCHAR(MAX) NOT NULL
--);

--INSERT INTO TB_USER (id, name, password) VALUES
	--(1, 'user', 'mpce12345'),
	--(2, 'default', 'mpce12345'),
	--(3, 'mpce', 'mpce12345');
	


DROP TABLE IF EXISTS TB_FILE;

CREATE TABLE TB_FILE (
	id INTEGER  PRIMARY KEY AUTO_INCREMENT,
	url VARCHAR(255) NOT NULL,
	createdAt TIMESTAMP
);
	